; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=VisualFigaro
AppVerName=VisualFigaro v1.11 : plugin for jEdit
AppPublisher=EDF R&D MRI
AppPublisherURL=http://www.edf.fr
;AppSupportURL=http://rdsoft.edf.fr
;AppUpdatesURL=http://rdsoft.edf.fr

UsePreviousAppDir=yes
DefaultDirName={pf}\jEdit
DirExistsWarning=no
DefaultGroupName=EDF MRI Tools
AppCopyright=Copyright © EDF
InfoAfterFile=..\..\2_Exe\EnglishFrancais\ReadMe.txt
;WizardImageFile=..\..\..\..\Logos\logoofficielEDF.bmp
; Si on ne précise pas OutputDir, l'installateur est mis dans SourceDir\Output
OutputDir=..\..\4_Packages_livrables\EnglishFrancais\Output
OutputBaseFilename=VisualFigaro V1.11

SourceDir=..\..\2_Exe\EnglishFrancais\
PrivilegesRequired=none


[Files]
; Le plugin lui-même
Source: *.jar; DestDir: {app}\jars; Flags: ignoreversion
; Le serveur de traitements KB3
Source: st.exe; DestDir: {app}\VisualFigaro; Flags: ignoreversion
Source: cpp_st.exe; DestDir: {app}\VisualFigaro; Flags: ignoreversion

; Les colorations de mots-clés
Source: figaro.xml; DestDir: {userdesktop}\..\.jedit\modes; Flags: ignoreversion
; Ajout de la déclaration du mode FIGARO pour Jedit
Source: catalog; DestDir: {userdesktop}\..\.jedit\modes; Flags: ignoreversion

Source: ReadMe.txt; DestDir: {app}\VisualFigaro; Flags: ignoreversion

; Le fichier d'aide syntaxique avec les expressions types en FIGARO français et anglais
;   + les fichiers de schémas et modèles permettant de démarrer une nouvelle bdc
Source: Jedit.VisualFigaro\*.*; DestDir: {app}\VisualFigaro; Flags: ignoreversion

; Les icônes standard
Source: Jedit.VisualFigaro\icons\*.*; DestDir: {app}\VisualFigaro\icons; Flags: ignoreversion

Source: ..\..\7_Tests\*.zip; DestDir: {app}\VisualFigaro\Tests; Flags: ignoreversion
Source: ..\..\7_Tests\*.txt; DestDir: {app}\VisualFigaro\Tests; Flags: ignoreversion

; Les fichiers du traducteur TradBdC
Source: Jedit.VisualFigaro\TradBdC\*.*; DestDir: {app}\VisualFigaro\TradBdC; Flags: ignoreversion
Source: Jedit.VisualFigaro\*.xsd; DestDir: {app}\VisualFigaro\TradBdC; Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
; La répertoire Temp_VF sert à la création des fichiers temporaires. Cette création doit pouvoir être
; réalisée sans avoir les droits administrateur
Name: {userdocs}\Temp_VF

[Registry]
; La variable d'environnement TMP_VF sert à la création des fichiers temporaires. Cette création doit pouvoir être
; réalisée sans avoir les droits administrateur
Root: HKLM; Subkey: SYSTEM\CurrentControlSet\Control\Session Manager\Environment; ValueType: string; ValueName: TMP_VF; ValueData: {userdocs}\Temp_VF\

; La variable d'environnement VISUAL_FIGARO sert aux programmes pour trouver le sous-répertoire VisualFigaro
; du répertoire d'installation de Jedit.
Root: HKLM; Subkey: SYSTEM\CurrentControlSet\Control\Session Manager\Environment; ValueType: string; ValueName: VISUAL_FIGARO; ValueData: {app}\VisualFigaro\

; Attention : cpp_st DOIT être dans le path, d'où l'instruction ci-dessous
Root: HKLM; Subkey: SYSTEM\CurrentControlSet\Control\Session Manager\Environment; ValueType: string; ValueName: Path; ValueData: "{reg:HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment,Path|Y:};{app}\VisualFigaro\"
