package global;

public enum WidgetClasses {
	NOWIDGET,
	WIDGET,
	ADDDEL,
	ADDDELEDIT,
	ADDDELUPDOWN,
	NODELINKNEITHERUPDOWNEDIT,
	COMBO,
	CONTROL,
	CONTROLEDLIST,
	CONTROLEDLISTADDDEL,
	FORMATTEDTEXTFIELD,
	GRIDFORM,
	MODIFIABLEGRIDFORM,
	LIST,
	LISTCOMPLEXARRAY,
	LISTSIMPLEARRAY,
	OKCANCEL,
	TEXTFIELD,
	EDITDEFAULTVAR,
	LOADICON,
	EXPRESSION
};
